### ISSUE TITLE
ActionView::Template::Error (undefined method `id' for nil:NilClass) when trying to create new Oauth application.

### ISSUE THREAD

**Issue by jt-moriarty** [nbgallery/nbgallery#631] opened 2021-12-10 21:39 UTC
Hello, I've been working on configuring a local deployment of NB-Gallery for testing and it's throwing a 500 error when I try to hit the "New Application" button on the "Your Applications" page for Oauth applications. 
-I followed the directions here (https://github.com/nbgallery/nbgallery/blob/main/docs/jupyter_hub_oauth.md) for enabling this feature.
-I looked at the production.rb log for the nbgallery container, and I'm including this section of the log pertaining to the error:
```
ActionView::Template::Error (undefined method 'id' for nil:NilClass):
    22:
    23:       <% if Doorkeeper.configuration.native_redirect_uri %>
    24:           <span class="form-text text-secondary">
    25:             <%= raw t('doorkeeper.applications.help.native_redirect_uri', native_redirect_uri: content_tag(:code, class: 'bg-light') { Doorkeeper.configuration.native_redirect_uri }) %>
    26:           </span>
    27:       <% end %>
    28:     </div>
  app/helpers/notebooks_helper.rb:104:in 'code'
  app/helpers/notebooks_helper.rb:120:in 'raw'
  ```
-There's nowhere in the displayed code that mentions an id, so I did some looking into Doorkeeper and it sounds like it might be an issue with resource_owner_authenticator or admin_authenticator blocks in https://github.com/nbgallery/nbgallery/blob/main/config/initializers/doorkeeper.rb, but I added some additional debug statements in those sections and it looks like it is finding the admin user and its id correctly.
I would appreciate any additional insight on this issue, and let me know if there is any more information I can provide.

**Comment by manfromjupyter** [comment] 2021-12-13 22:57
Hi @jt-moriarty, looks like the issue is here on the second line below. 

So `@user` is nil so finding `id` of it is coming up with nothing. That tells me it's not figuring out who you are signed in and that is the issue. You can check the UserPreferences table in your SQL to see if that user_id has a record, but even if you are viewing the software without signing in (if you have public allowed), you should be able to render code cells just fine (just tested it). For some reason the authentication is not working. I recognize that's what you're working on, but might need want to try printing your debug statements from that notebook_helper.

What I'd recommend is check to see if you can render all non-notebook pages. If you can do that and code cells are only problem then maybe on our end we need to do a nil catch or user has no user preference check (despite everyone automatically creating a record in that table to me knowledge).

Code where the "id" comes from. Line 104 of `app/helpers/notebooks_helper.rb`
```
def code(lang, text)
    user_pref = UserPreference.find_by(user_id: @user.id)
    lang = 'text' if lang.blank?
    if user_pref && user_pref.disable_row_numbers
      markdown "```#{lang}\n#{text}\n```"
    else
      formatter = Rouge::Formatters::HTML.new
      begin
        output=Rouge.highlight text, lang, Rouge::Formatters::HTMLLinewise.new(formatter, class: "code-block")
      rescue StandardError
        output=Rouge.highlight text, 'text', Rouge::Formatters::HTMLLinewise.new(formatter, class: "code-block")
      end
      output = "<pre class=\"Highlight\">" + output + "</pre>"
    end
  end
  ```

**Comment by jt-moriarty** [comment] 2021-12-14 21:05
Hi, thanks for the added direction! Using it I was able to figure out that @user in the snippet above is nil for some unknown reason (despite my being logged in as an admin user) so I was able to add `@user = current_user if @user.nil?` which resolved the problem, though it does leave me concerned that some user setup or login code isn't running fully correctly.

**Comment by mcrutch** [comment] 2022-07-27 11:36
Closing this due to the merge we did a few months ago.  If the error pops back up we can reinvestigate.

**Closed by mcrutch** 2022-07-27 11:36 UTC
