### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by cccs-cat001** [nbgallery/nbgallery#249] opened 2020-07-28 11:48 UTC
Hi, I have NBGallery set up. It has an email address and db and all that and it all seems to be working. When I go to register, nothing happens it remains on the register screen. I check the db and my user info is there, so something happened. And I never receive an email from nbgallery asking me to confirm my email. 

Can someone help me debug this, I'm not a ruby dev by any means...

Also is there a way to remove auth and just have it open to everyone?

**Comment by mcrutch** [comment] 2020-07-28 13:19
There isn't any way to remove auth entirely because user objects are needed to relate to the other objects.   

The problem most likely stems from the fact that the email server is not properly configured so the confirmation email never gets sent so the account isn't activated.  For testing purposes until you can get email configuration sorted out you can set users.confirmed_at to the current date and users.approved=1 for the user in the mysql database. That should do it. 

I will say the EASIEST way to get auth working long-term is to use one (or more) of the oauth provider options, gitlab, github, google, or facebook, that are available.  

See: https://github.com/nbgallery/nbgallery/blob/master/docs/configuration.md for information about the email configuration and the oauth documentation. (Although I have to add the link to the gitlab side of the documentation, forgot that)

**Comment by mcrutch** [comment] 2020-07-28 13:33
Oh, btw, email configuration is required for some of the features to work so you have to get that sorted out anyway (Change requests, feedback, shares) but for development purposes I have been using docker image gessnerfl/fake-smtp-server and forcing it to listen on port 587.

  smtp:
    image: gessnerfl/fake-smtp-server:latest
    ports:
      - "5080:5080"
      - "5081:5081"
      - "587:5025"
    restart: always
THen passing the appropriate EMAIL_SERVER, EMAIL_DOMAIN, GALLERY__EMAIL__GENERAL_FROM and EMAIL_DEFAULT_URL_OIPTIONS_HOST environment variables to the docker container.  I will write this up in more detail sometime.

**Comment by cccs-cat001** [comment] 2020-07-28 13:39
See, I'd like to use oauth, but we use azure AD, which isn't listed for nbgallery. The email server I have set up is just a relay listening on port 25. Would there be any issue with changing the port to be 25 instead of 587?

**Comment by mcrutch** [comment] 2020-07-28 13:41
There is a ticket for doing a sample ldap authentication plugin, but it hasn't bubbled to the top of the stack.  

I also opened #250 to allow configuring the email port.

**Comment by cccs-cat001** [comment] 2020-07-28 13:48
Cool thanks

**Comment by cccs-cat001** [comment] 2020-07-28 13:49
can a ticket be opened as well to add Azure OAuth, or even JWT authentication? Or both?

**Comment by mcrutch** [comment] 2020-07-28 14:07
If the gems are compatible with what we have so far, we SHOULD be able to add Azure simply, but I don't have an environment to test it with. 
(leaving here for myself) https://github.com/marknadig/omniauth-azure-oauth2

**Comment by cccs-cat001** [comment] 2020-07-28 16:08
I changed the relay server to open port 587, and it's still not working.. Does it not work for relays? Do I need an actual email account on this server?

**Comment by mcrutch** [comment] 2020-07-28 16:20
Ok, closing this one out.  Pull request is in for #250 follow #253 for azure (and I might try and tag you in that ticket if I need someone to test it)

**Comment by mcrutch** [comment] 2020-07-28 16:36
Ooops, missed your comment before I closed this. ...if you aren't required to login to the server it should still work, or if you are, you can supply username/password.

**Comment by mcrutch** [comment] 2020-07-28 16:44
So, just to loop back on this...after you changed the port the mail server was listening to, did you attempt to register with a different email account? Because the registration is what triggers the confirmation email.  Another thought would be to force confirmation by updating the confirmed_at date in the database for the user, uploading a notebook, and keep trying to issue "feedback" until you can get emails working, then go back and try a user registration again.

**Comment by mcrutch** [comment] 2020-07-28 17:00
So, I will say (and this caught me a couple times) that the things you need the most are
EMAIL_SERVER
EMAIL_DOMAIN
GALLERY__EMAIL__GENERAL_FROM (note the double __ between Gallery and Email and Email and General)
EMAIL_DEFAULT_URL_OPTIONS_HOST
If any of those aren't set, you are going to have a bad day.

**Comment by cccs-cat001** [comment] 2020-07-28 17:05
What's GALLERY__EMAIL__GENERAL_FROM? I've never seen that before.

**Comment by mcrutch** [comment] 2020-07-28 17:09
Something I just realized was never documented (and not sure how old it is) 
It overrides the value config.email.general_from which is set to empty string in config/settings.yml.  I just updated the configuration docs for that.

**Comment by cccs-cat001** [comment] 2020-07-28 17:27
If I remove my one email from the db would that allow the registration trigger to happen again?

**Comment by mcrutch** [comment] 2020-07-28 17:28
Yeah, delete that row from users, and try again.

**Comment by cccs-cat001** [comment] 2020-07-28 17:33
Still no go :frowning_face:  Is there a way I can turn on some debug logs in the docker image? Maybe that'll output some info?

**Comment by mcrutch** [comment] 2020-07-28 17:49
Since that container is running just puma, the output should be available by docker logs on the container, you are looking for "ActionMailer"
If you can't get the logs but can exec in, you are looking for /usr/src/nbgallery/log/*.log
Container has /bash and /sh
Make sure you are running nbgallery/nbgallery:latest because that has debug set in production (/usr/src/nbgallery/config/environments/production.rb in the container)
At some point I may try and share a more production friendly config that runs passenger and httpd as the server, but just isn't on my radar right now.

**Comment by mcrutch** [comment] 2020-07-28 18:10
Doing some digging on my own container and I hit "ArgumentError (SMTP From address may not be blank)" when attempting to register a new user, so it looks like that is not propagating fully.  Still looking

**Comment by mcrutch** [comment] 2020-07-28 18:19
Ok, MY problem was I didn't also have EMAIL_ADDRESS (which is in the docs) which is the from address for the confirmation email.
So,
EMAIL_ADDRESS
EMAIL_SERVER
EMAIL_DOMAIN
EMAIL_DEFAULT_URL_OPTIONS_HOST
GALLERY__EMAIL__GENERAL_FROM (note the double __ between Gallery and Email and Email and General) (for all other emails apparently)
Those are the ONLY email variables I set for my dev site and it all works.

**Comment by cccs-cat001** [comment] 2020-07-28 19:31
Hmm.. found the logs. When I click register I get this: 
```
[2020-07-28T19:27:16.994795 #49]  INFO -- : Started POST "/users.json" for 10.244.1.38 at 2020-07-28 19:27:16 +0000
I, [2020-07-28T19:27:16.997826 #49]  INFO -- : Processing by RegistrationsController#create as JSON
I, [2020-07-28T19:27:16.997888 #49]  INFO -- :   Parameters: {"utf8"=>"✓", "user"=>{"user_name"=>"test", "email"=>"<email>", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Register"}
D, [2020-07-28T19:27:17.148463 #49] DEBUG -- :    (0.3ms)  BEGIN
D, [2020-07-28T19:27:17.152799 #49] DEBUG -- :   User Exists (0.4ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY '<email>' LIMIT 1
D, [2020-07-28T19:27:17.153929 #49] DEBUG -- :   User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = <email>' LIMIT 1
D, [2020-07-28T19:27:17.154622 #49] DEBUG -- :   User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`user_name` = BINARY 'test' LIMIT 1
D, [2020-07-28T19:27:17.156553 #49] DEBUG -- :   SQL (0.4ms)  INSERT INTO `users` (`email`, `encrypted_password`, `user_name`, `created_at`, `updated_at`, `confirmation_token`, `confirmation_sent_at`) VALUES (<email>', '$2a$11$0mEncfIe.2uStVcp5NUDyuI0ty/bOru7HflsIC98Ag1mQ1JoYxB/S', 'test', '2020-07-28 19:27:17', '2020-07-28 19:27:17', 'jPu8RCe9jdQHQ-PSxYZ4', '2020-07-28 19:27:17')
D, [2020-07-28T19:27:17.157824 #49] DEBUG -- :   SQL (0.3ms)  INSERT INTO `preferences` (`easy_buttons`, `user_id`, `created_at`, `updated_at`) VALUES (1, 16, '2020-07-28 19:27:17', '2020-07-28 19:27:17')
D, [2020-07-28T19:27:17.159926 #49] DEBUG -- :   SQL (0.3ms)  INSERT INTO `user_summaries` (`user_id`, `created_at`, `updated_at`) VALUES (16, '2020-07-28 19:27:17', '2020-07-28 19:27:17')
D, [2020-07-28T19:27:17.166260 #49] DEBUG -- :    (5.7ms)  COMMIT
I, [2020-07-28T19:27:17.182009 #49]  INFO -- :   Rendered devise/mailer/confirmation_instructions.html.slim (4.6ms)
D, [2020-07-28T19:27:17.388437 #49] DEBUG -- : 
Devise::Mailer#confirmation_instructions: processed outbound mail in 218.8ms
I, [2020-07-28T19:27:17.405753 #49]  INFO -- : 
Sent mail to<email> (17.1ms)
D, [2020-07-28T19:27:17.405812 #49] DEBUG -- : Date: Tue, 28 Jul 2020 19:27:17 +0000
From: <nb email>
Reply-To: <nb email>
To: <email>
Message-ID: <5f207c1560550_312af52d4c3a682536@nbgallery-6bf9ccf76-c5sjr.mail>
Subject: Confirmation instructions
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Welcome <email>!</p><p>You can confirm your account email through the link below:</p><p><a href="http://ops.cyber.gc.ca/users/confirmation?confirmation_token=jPu8RCe9jdQHQ-PSxYZ4">Confirm my account</a></p>
I, [2020-07-28T19:27:17.406182 #49]  INFO -- : Completed 500 Internal Server Error in 408ms (ActiveRecord: 8.4ms)
F, [2020-07-28T19:27:17.407611 #49] FATAL -- : 
Net::SMTPSyntaxError (503 5.5.1 Invalid command: Command not supported
):
  /usr/local/lib/ruby/2.3.0/net/smtp.rb:992:in `check_auth_continue'
  /usr/local/lib/ruby/2.3.0/net/smtp.rb:748:in `block in auth_login'
  /usr/local/lib/ruby/2.3.0/net/smtp.rb:965:in `critical'
  /usr/local/lib/ruby/2.3.0/net/smtp.rb:747:in `auth_login'
  /usr/local/lib/ruby/2.3.0/net/smtp.rb:733:in `authenticate'
  /usr/local/lib/ruby/2.3.0/net/smtp.rb:568:in `do_start'
  /usr/local/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
  vendor/bundle/ruby/2.3.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
  vendor/bundle/ruby/2.3.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
  vendor/bundle/ruby/2.3.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
  vendor/bundle/ruby/2.3.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
  vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.11.3/lib/action_mailer/base.rb:543:in `block in deliver_mail'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.11.3/lib/action_mailer/base.rb:541:in `deliver_mail'
  vendor/bundle/ruby/2.3.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
  vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.11.3/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
  vendor/bundle/ruby/2.3.0/gems/devise-4.7.1/lib/devise/models/authenticatable.rb:199:in `send_devise_notification'
  vendor/bundle/ruby/2.3.0/gems/devise-4.7.1/lib/devise/models/confirmable.rb:121:in `send_confirmation_instructions'
  vendor/bundle/ruby/2.3.0/gems/devise-4.7.1/lib/devise/models/confirmable.rb:183:in `send_on_create_confirmation_instructions'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:253:in `block in conditional'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:506:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:506:in `each'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:506:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:778:in `_run_commit_callbacks'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:314:in `committed!'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:89:in `commit_records'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:153:in `commit'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:175:in `commit_transaction'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `within_new_transaction'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:286:in `block in save'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:285:in `save'
  vendor/bundle/ruby/2.3.0/gems/devise-4.7.1/app/controllers/devise/registrations_controller.rb:19:in `create'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:117:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:505:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.3.0/gems/actionview-4.2.11.3/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/routing/route_set.rb:43:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/routing/mapper.rb:49:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/routing/route_set.rb:817:in `call'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
  vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
  vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/conditionalget.rb:38:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:252:in `context'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/session/abstract/id.rb:247:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.3.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/static.rb:120:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.3/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.3/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/content_length.rb:15:in `call'
  vendor/bundle/ruby/2.3.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
  vendor/bundle/ruby/2.3.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
  vendor/bundle/ruby/2.3.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
  vendor/bundle/ruby/2.3.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
  vendor/bundle/ruby/2.3.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'


I, [2020-07-28T19:27:17.415474 #49]  INFO -- : Processing by Gaffe::ErrorsController#show as JSON
I, [2020-07-28T19:27:17.415537 #49]  INFO -- :   Parameters: {"utf8"=>"✓", "user"=>{"user_name"=>"test", "email"=>"<email>", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Register"}
I, [2020-07-28T19:27:17.422635 #49]  INFO -- :   Rendered errors/internal_server_error.slim within layouts/error (3.2ms)
I, [2020-07-28T19:27:17.426453 #49]  INFO -- : Completed 500 Internal Server Error in 11ms (Views: 9.5ms | ActiveRecord: 0.0ms | Solr: 0.0ms)
```

**Comment by mcrutch** [comment] 2020-07-28 20:14
Reminders for me tomorrow:
https://github.com/huginn/huginn/issues/1657
https://stackoverflow.com/questions/26093514/rails-actionmailer-send-email-without-authentication
https://github.com/nbgallery/nbgallery/blob/master/config/environments/production.rb#L95

I think line 95 and 96 have to go away if there isn't any login/password for the SMTP server.

**Comment by mcrutch** [comment] 2020-07-29 11:43
So, that error looks like there was an error talking to your SMTP server, and from a quick google yesterday I might have found the solution, so try this container image if you can: nbgallery/nbgallery:email-port-configuration  
If that works for you, it should be able to be merged into the master branch.

**Comment by cccs-cat001** [comment] 2020-07-29 11:49
Eeeyyyyy!!! That works! Thank you for all the help!

**Comment by mcrutch** [comment] 2020-07-29 11:52
Ok, once that branch merges the latest image will rebuild and you will be good to go.

**Comment by cccs-cat001** [comment] 2020-07-29 11:54
Awesome! Thank you :)

**Closed** 2020-07-30 15:38 UTC
