### ISSUE TITLE
Change requests still submit but somehow for some people some times return a json error message

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#474] opened 2021-02-25 21:41 UTC
Despite filling out the comments sections, more than 1 user has reported they keep getting a `"Error: {"message":"not found"}` json alert/pop up.

**Comment by mcrutch** [comment] 2021-03-05 12:26
That sounds like it couldn't load the notebook it was trying to push the change request to.  Did the permissions on the notebook change? Did the notebook get deleted before they submitted their change request?

**Comment by manfromjupyter** [comment] 2021-03-05 16:43
No idea. Haven't been able to repro it myself, but will check (but think the change request has deleted because it was 8/9 days ago

**Comment by alexanghh** [comment] 2021-06-04 08:17
This happens for me when I submit the change request via jupyter notebook. It doesn't happen when I submit via nbgallery.

**Comment by mcrutch** [comment] 2022-12-29 17:48
So, the staging happening twice is a Jupyter extension problem and probably needs to be addressed in https://github.com/nbgallery/lab-extensions.

**Comment by mcrutch** [comment] 2022-12-29 17:49
Could potentially catch double stage too, but then would trigger double open from the extensions...so...yeah, probably look to fix in the extension

**Comment by mcrutch** [comment] 2023-03-01 12:40
I have seen this before, but for the life of me can't reproduce it right now to see what might be causing it.

**Comment by manfromjupyter** [comment] 2023-03-02 15:06
@mcrutch are we still seeing users every so occasionally with this issue? If so, maybe we need to reach out to them directly

**Comment by mcrutch** [comment] 2023-09-25 12:34
Going to close this one anyway because the correct side is from the extension and we haven't seen any grumbling so I might have inadvertently fixed it at some point.

**Closed by mcrutch** 2023-09-25 12:34 UTC
Labels: research
