### ISSUE TITLE
Error handle and enforce requiring emails not usernames for sharing notebooks

### ISSUE THREAD

**Issue by manfromjupyter** [nbgallery/nbgallery#413] opened 2021-01-12 19:12 UTC
When sharing a notebook with a user and adding them by their username and not their email (unless they're the same obviously) causes the share to silently fail and then refreshes the page. Need to be more dummy proof so recommend:
- Change input field's type to that of "email" so the browser disables the submit button until an email is entered
- Update the placeholder text from "Enter usernames" to "Enter emails"
- Enable some kind of error handling if this browser handling of our view fails and the user email was not entered in correctly or whatever.

**Comment by jeffyjefflabs** [comment] 2021-01-12 20:41
Yeah this was always gross and I don't know what the best strategy is.  On the one hand users don't necessarily know each other's emails since the site should keep those private (except in scenarios where they match, of course), but on the other hand some sort of notification is implied.  Maybe part of the problem is the way we use "share" to mean not only "hey you should check out this notebook" (which only requires an email, regardless of whether the shared-with user has an account) but also "you're now a part-owner" (which only makes sense if the shared-with user *does* have an account, in which case sharing by username makes sense).

**Comment by manfromjupyter** [comment] 2021-01-12 20:44
Oh I see the predicament lol. Geez

**Comment by mcrutch** [comment] 2021-01-19 16:56
I think sharing should stay as "username" only allow tokenized values, but allow searching for users by username OR email address (but still only tokenize the user name).  In fact, it should probably act more like group membership than it currently does so it is clear that they aren't RE-sharing with the same people if they go to share again, but instead, keeping them on the list of shared people.

**Comment by mcrutch** [comment] 2021-03-11 14:17
We will continue to default to usernames, share by email is disabled by default in the pull request I just submitted (since the code to share by email is a completely stub and doesn't send any emails) and an appropriate error message is generated about it being shared by username only if share by email is disabled.

**Comment by mcrutch** [comment] 2021-03-25 09:59
Decided the dialog as-is is fine and the functionality change of the linked Pull request will count as closing this.

**Closed** 2021-03-31 12:46 UTC
